//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.JskSciurus17Teleop
{
    [Serializable]
    public class CancelRosbagRequest : Message
    {
        public const string k_RosMessageName = "jsk_sciurus17_teleop/CancelRosbag";
        public override string RosMessageName => k_RosMessageName;

        //  CancelRosbag.srv

        public CancelRosbagRequest()
        {
        }
        public static CancelRosbagRequest Deserialize(MessageDeserializer deserializer) => new CancelRosbagRequest(deserializer);

        private CancelRosbagRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "CancelRosbagRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
