//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.JskSciurus17Teleop
{
    [Serializable]
    public class StartRosbagRequest : Message
    {
        public const string k_RosMessageName = "jsk_sciurus17_teleop/StartRosbag";
        public override string RosMessageName => k_RosMessageName;

        public string bag_name;

        public StartRosbagRequest()
        {
            this.bag_name = "";
        }

        public StartRosbagRequest(string bag_name)
        {
            this.bag_name = bag_name;
        }

        public static StartRosbagRequest Deserialize(MessageDeserializer deserializer) => new StartRosbagRequest(deserializer);

        private StartRosbagRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.bag_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.bag_name);
        }

        public override string ToString()
        {
            return "StartRosbagRequest: " +
            "\nbag_name: " + bag_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
