//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.JskSciurus17Teleop
{
    [Serializable]
    public class StopRosbagRequest : Message
    {
        public const string k_RosMessageName = "jsk_sciurus17_teleop/StopRosbag";
        public override string RosMessageName => k_RosMessageName;

        //  StopRosbag.srv

        public StopRosbagRequest()
        {
        }
        public static StopRosbagRequest Deserialize(MessageDeserializer deserializer) => new StopRosbagRequest(deserializer);

        private StopRosbagRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "StopRosbagRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
